
#With default value every difficulty perk maxes out at difficulty 250
[general]
	#Disable/Enables the whole difficulty scaling of this mod. Requires a mc restart
	"Enable difficulty scaling" = true
	#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
	"Difficulty Delay" = 0
	#Wether difficulty should only increase with at least one online players or not
	"Ignore Players" = false
	#Mobs to include for the new light spawning rules.
	"Light list" = []
	#Turn the list list whitelist to blacklist
	"Light list blacklist" = false
	#Light level >= x will prevent mob spawning for defined mobs.
	#Range: 0 ~ 16
	Light = 7
	#Should punish time skipping with e.g. bed, commands? If false, difficulty will increase by 0.1 regardless of skipped time.
	"Punish Time Skip" = true
	#Disable/Enable friendly fire for owned pets.
	FriendlyFire = false
	#Blacklist for pet you should't be able to give armor to. Pets from mods, which have custom armor should be included here.
	"Pet Blacklist" = []
	#Treat pet blacklist as whitelist
	"Pet Whitelist" = false
	#Increase difficulty with time
	#Here untill its back as a gamerule
	"Difficulty toggle" = true

#Black/Whitelist for various stuff
[list]
	#By default the mod only modifies EntityMobs. Add other entities here if you want to apply modifications to them. Usage:
	#<entity registry name> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,SWIMMRIDE,TARGETVILLAGER,REVERSE].
	#Leave empty to apply them all and REVERSE to reverse all flags. Some flags do nothing for certain mobs!
	#example: minecraft:sheep|REVERSE|ATTRIBUTES will add sheep to attributes modification (since default is a blacklist)
	#or minecraft:sheep|ATTRIBUTES will add sheep to everything except attributes
	"More Entities" = ["alexsmobs:centipede_tail", "ars_nouveau:wixie", "alexsmobs:snow_leopard", "villigeandmonstermod:hipopotam", "alexsmobs:lobster", "minecolonies:archerpirate", "aquaculture:pink_salmon", "alexsmobs:moose", "alexsmobs:seal", "betteranimalsplus:octopus", "betterendforge:dragonfly", "productivebees:bumble_bee", "aquaculture:atlantic_herring", "villigeandmonstermod:zubr", "alexsmobs:shoebill", "alexsmobs:roadrunner", "minecraft:trader_llama", "wyrmroost:alpine", "upgrade_aquatic:goose", "wyrmroost:lesser_desertwyrm", "upgrade_aquatic:thrasher", "productivebees:creeper_bee", "rats:rat_baron", "rats:ratfish", "alexsmobs:endergrade", "minecraft:horse", "ars_nouveau:wilden_stalker", "villigeandmonstermod:golob", "productivebees:green_carpenter_bee", "aquaculture:muskellunge", "betteranimalsplus:bobbit_worm", "aquaculture:bayad", "minecraft:llama", "minecolonies:amazonchief", "ars_nouveau:sylph", "aquaculture:bluegill", "wyrmroost:royal_red", "villigeandmonstermod:bober", "villigeandmonstermod:deer", "villigeandmonstermod:stone_pig", "betteranimalsplus:nautilus", "minecraft:dolphin", "upgrade_aquatic:immortal_jellyfish", "betteranimalsplus:flying_fish", "villigeandmonstermod:green_magic_fish", "alexsmobs:komodo_dragon", "minecolonies:pirate", "alexsmobs:hammerhead_shark", "minecolonies:mercenary", "minecraft:donkey", "minecolonies:shieldmaiden", "betteranimalsplus:eel_freshwater", "upgrade_aquatic:box_jellyfish", "alexsmobs:grizzly_bear", "quark:stoneling", "buzzier_bees:grizzly_bear", "villigeandmonstermod:jez", "minecolonies:archerbarbarian", "villigeandmonstermod:pigeno", "minecraft:bee", "aquaculture:perch", "villigeandmonstermod:big_pig", "villigeandmonstermod:goose", "productivebees:sweaty_bee", "alexsmobs:crocodile", "quark:toretoise", "betteranimalsplus:moose", "villigeandmonstermod:goryl", "betteranimalsplus:badger", "minecolonies:barbarian", "the_bumblezone:honey_slime", "quark:frog", "productivebees:yellow_black_carpenter_bee", "aquaculture:jellyfish", "minecraft:mooshroom", "villigeandmonstermod:bigggggggg", "villigeandmonstermod:marmot", "rats:plague_doctor", "minecraft:villager", "aquaculture:tuna", "villigeandmonstermod:snowy_coat", "rats:ghost_pirat", "betteranimalsplus:eel_saltwater", "iceandfire:ice_dragon", "rats:rat", "villigeandmonstermod:kojot", "alexsmobs:blobfish", "botania:doppleganger", "betteranimalsplus:turkey", "productivebees:mason_bee", "minecolonies:chiefpirate", "alexsmobs:gorilla", "productivebees:hoarder_bee", "upgrade_aquatic:great_thrasher", "rats:rat_mount_automaton", "aquaculture:blackfish", "aquaculture:arapaima", "minecraft:strider", "minecraft:parrot", "quark:crab", "betteranimalsplus:feralwolf", "productivebees:rancher_bee", "minecraft:wandering_trader", "villigeandmonstermod:mors", "aquaculture:carp", "betteranimalsplus:piranha", "aquaculture:pacific_halibut", "productivebees:blue_banded_bee", "iceandfire:sea_serpent", "villigeandmonstermod:seagull", "minecraft:iron_golem", "productivebees:nomad_bee", "betteranimalsplus:barracuda", "iceandfire:mob_skull", "botania:pixie", "mutantbeasts:spider_pig", "villigeandmonstermod:chomik", "productivebees:ashy_mining_bee", "betteranimalsplus:coyote", "betteranimalsplus:squirrel", "quark:leash_knot_fake", "aquaculture:boulti", "villigeandmonstermod:peacock", "alexsmobs:hummingbird", "betteranimalsplus:dragonfly", "villigeandmonstermod:zelaznykurczak", "upgrade_aquatic:cassiopea_jellyfish", "rats:rat_spawner", "upgrade_aquatic:flare", "villigeandmonstermod:tukan", "betteranimalsplus:songbird", "villigeandmonstermod:bullfinch", "minecraft:mule", "villigeandmonstermod:big_bro", "betteranimalsplus:pheasant", "alexsmobs:crow", "betteranimalsplus:blackbear", "aquaculture:atlantic_cod", "rats:rattling_gun", "minecolonies:chiefbarbarian", "mutantbeasts:creeper_minion", "alexsmobs:centipede_body", "betteranimalsplus:jellyfish", "aquaculture:synodontis", "villigeandmonstermod:magic_yellow_fish", "productivebees:configurable_bee", "minecraft:pufferfish", "buzzier_bees:bumblebee", "aquaculture:starshell_turtle", "minecraft:fox", "aquaculture:smallmouth_bass", "betteranimalsplus:lammergeier", "wyrmroost:canari_wyvern", "mekanism:robit", "villigeandmonstermod:rys", "alexsmobs:warped_toad", "minecraft:chicken", "wyrmroost:roost_stalker", "betteranimalsplus:whale", "ars_nouveau:whelp", "upgrade_aquatic:pike", "productivebees:leafcutter_bee", "villigeandmonstermod:earth_golem", "alexsmobs:cockroach", "aquaculture:minnow", "buzzier_bees:moobloom", "aquaculture:tambaqui", "betterendforge:end_fish", "betteranimalsplus:goose", "wyrmroost:dragon_fruit_drake", "minecraft:hoglin", "aquaculture:catfish", "ars_nouveau:wilden_hunter", "alexsmobs:capuchin_monkey", "iceandfire:dread_horse", "rats:rat_mount_biplane", "aquaculture:brown_shrooma", "upgrade_aquatic:glow_squid", "productivebees:digger_bee", "iceandfire:myrmex_swarmer", "minecraft:polar_bear", "iceandfire:lightning_dragon", "upgrade_aquatic:nautilus", "productivebees:dye_bee", "iceandfire:dragon_skull", "aquaculture:brown_trout", "minecraft:pig", "minecraft:turtle", "alexsmobs:alligator_snapping_turtle", "aquaculture:red_shrooma", "minecraft:sheep", "betteranimalsplus:butterfly", "aquaculture:atlantic_halibut", "minecraft:ender_dragon", "productivebees:cupid_bee", "rats:rat_mount_strider", "alexsmobs:rattlesnake", "iceandfire:fire_dragon", "quark:foxhound", "betteranimalsplus:brownbear", "minecraft:cod", "productivebees:neon_cuckoo_bee", "aquaculture:gar", "betteranimalsplus:squid_giant", "alexsmobs:mantis_shrimp", "villigeandmonstermod:wodnagadzina", "aquaculture:red_grouper", "minecolonies:visitor", "minecolonies:norsemenarcher", "villigeandmonstermod:rr", "alexsmobs:raccoon", "minecolonies:citizen", "minecraft:squid", "rats:rat_protector", "minecraft:skeleton_horse", "rats:rat_mount_golem", "betteranimalsplus:walrus", "iceandfire:myrmex_soldier", "minecraft:cow", "minecolonies:amazon", "aquaculture:rainbow_trout", "alexsmobs:fly", "iceandfire:hippocampus", "minecolonies:archermummy", "productivebees:lumber_bee", "iceandfire:pixie", "upgrade_aquatic:ululu", "villigeandmonstermod:pheasant", "majruszs_difficulty:pillager_wolf", "villigeandmonstermod:blue_magic_fish", "minecraft:salmon", "iceandfire:myrmex_queen", "upgrade_aquatic:lionfish", "rats:rat_mount_chicken", "rats:rat_baron_plane", "rats:pirat", "minecraft:snow_golem", "rats:rat_mount_beast", "mutantbeasts:mutant_snow_golem", "iceandfire:myrmex_sentinel", "betterendforge:silk_moth", "wyrmroost:silver_glider", "iceandfire:myrmex_royal", "minecraft:rabbit", "artifacts:mimic", "betteranimalsplus:shark", "betteranimalsplus:deer", "aquaculture:piranha", "productivebees:reed_bee", "aquaculture:box_turtle", "villigeandmonstermod:mushroom_pig", "alexsmobs:orca", "alexsmobs:mungus", "ars_nouveau:wilden_guardian", "minecraft:bat", "alexsmobs:spectre", "betterendforge:cubozoa", "iceandfire:amphithere", "ars_nouveau:summon_horse", "minecolonies:mummy", "betteranimalsplus:crab", "betteranimalsplus:horseshoecrab", "aquaculture:pollock", "wyrmroost:butterfly_leviathan", "villigeandmonstermod:viking_villarger", "villigeandmonstermod:snowcow", "buzzier_bees:black_bear", "wyrmroost:coin_dragon", "aquaculture:arrau_turtle", "alexsmobs:elephant", "rats:demon_rat", "villigeandmonstermod:flying_pig", "aquaculture:capitaine", "villigeandmonstermod:light_snail", "alexsmobs:gazelle", "productivebees:chocolate_mining_bee", "wyrmroost:overworld_drake", "rats:pirat_boat", "betteranimalsplus:boar", "villigeandmonstermod:penguin", "minecraft:zombie_horse", "alexsmobs:sunbird", "iceandfire:cockatrice", "iceandfire:myrmex_worker", "villigeandmonstermod:rat", "minecraft:cat", "alexsmobs:stradpole", "productivebees:farmer_bee", "productivebees:resin_bee", "ars_nouveau:summon_wolf", "minecraft:tropical_fish", "iceandfire:hippogryph", "villigeandmonstermod:scarecrow", "betteranimalsplus:goat", "minecolonies:pharao", "minecraft:ocelot", "iceandfire:deathworm", "productivebees:quarry_bee", "minecolonies:norsemenchief", "betteranimalsplus:squid_colossal", "minecraft:wolf", "betteranimalsplus:reindeer", "betteranimalsplus:lamprey", "minecraft:panda", "ars_nouveau:carbuncle", "villigeandmonstermod:raven"]
	#Treat ATTRIBUTES flags as whitelist
	"Attribute Whitelist" = false
	#Treat ARMOR flags as whitelist
	"Armor Equip Whitelist" = false
	#Treat HELDITEMS flags as whitelist
	"Held Equip Whitelist" = false
	#Treat BLOCKBREAK flags as whitelist
	"Breaker Whitelist" = false
	#Treat USEITEM flags as whitelist
	"Item Use Whitelist" = false
	#Treat LADDER flags as whitelist
	"Ladder Whitelist" = false
	#Treat STEAL flags as whitelist
	"Steal Whitelist" = false
	#Treat SWIMMRIDE flags as whitelist
	"Boat Whitelist" = false
	#Treat TARGETVILLAGER flags as whitelist
	"Villager Whitelist" = false

#Debugging
[debug]
	#Enable showing of entity paths
	"Path Debugging" = false

#Settings for mod integration
[integration]
	#Should the scaling health mods difficulty system be used instead of this ones. (Requires scaling health mod)
	"Use Scaling Health Mod" = true
	#Should mobs be able to use techguns weapons. (Requires techguns mod)
	"Use Techguns Mod" = true
	#Should mobs be able to use weapons from the reforged mod. (Requires reforged mod)
	"Use Reforged Mod" = true
	#Should the coroutils repair block be used. (Requires coroutils mod)
	"Use CoroUtils Mod" = true

#Settings regarding custom ai for mobs
[ai]
	#Whitelist for blocks, which can be actively broken. Usage: <registry name;classname;tag> put "!" infront to exclude blocks
	"Block Whitelist" = ["forge:glass", "forge:glass_panes", "minecraft:fence_gates", "forge:fence_gates", "minecraft:wooden_doors"]
	#Treat Block Whitelist as Blocklist
	"Block as BlacklistBlock as Blacklist" = false
	#Use the block breaking sound instead of a knocking sound
	Sound = false
	#Chance for a mob to be able to break blocks
	#Range: 0.0 ~ 1.0
	"Breaker Chance" = 0.3
	#Chance for a mob to be able to steal items
	#Range: 0.0 ~ 1.0
	"Stealer Chance" = 0.3
	#Item which will be given to mobs who can break blocks. Set to nothing to not give any items.
	"Breaking item" = "minecraft:diamond_pickaxe"
	#Should mobs be able to break tile entities? Evaluated before the break list
	"Break Tiles" = true
	#Chance for neutral mobs to be aggressive
	#Range: 0.0 ~ 1.0
	"Neutral Aggressive Chance" = 0.2
	#List for of pairs containing which mobs auto target others. Syntax is [mob id]-[mob id] where second value is the target.
	# e.g. minecraft:zombie-minecraft:skeleton makes all zombies target skeletons
	"Auto Target List" = []
	#Delay for the coroutil repair block. Coroutil integration needs to be enabled
	"Repair Ticks" = 500
	#Difficulty at which mobs are able to break blocks
	"Difficulty Break AI" = 0.0
	#Difficulty at which mobs are able to steal items
	"Difficulty Steal AI" = 0.0

#Configs regarding mobs spawning with equipment
[equipment]
	#Blacklist for mods. Add modid to prevent items from that mod being used. (For individual items use the equipment.json)
	"Item Blacklist" = []
	#Use blacklist as whitelist
	"Item Whitelist" = false
	#Base chance that a mob can have one piece of armor
	#Range: 0.0 ~ 1.0
	"Equipment Chance" = 0.1
	#Base chance for each additional armor pieces
	#Range: 0.0 ~ 1.0
	"Additional Equipment Chance" = 0.3
	#Adds additional x*difficulty% to base equip chance
	"Equipment Addition" = 0.3
	#Chance for mobs to have a weapon
	#Range: 0.0 ~ 1.0
	"Weapon Chance" = 0.05
	#Adds additional x*difficulty% to base weapon chance
	"Weapon Chance Add" = 0.3
	#Base chance for each armor pieces to get enchanted
	#Range: 0.0 ~ 1.0
	"Enchanting Chance" = 0.2
	#Adds additional x*difficulty% to base enchanting chance
	"Enchanting Addition" = 0.2
	#Specify min and max enchanting levels according to difficulty. difficulty-minLevel-maxLevel
	"Enchanting Calc" = ["0-5-10", "25-5-15", "50-10-17", "100-15-25", "200-20-30", "250-30-35"]
	#Chance for mobs to have an item in offhand
	#Range: 0.0 ~ 1.0
	"Item Equip Chance" = 0.05
	#Adds additional x*difficulty% to base item chance
	"Item Chance add" = 0.2
	#Should mobs drop the armor equipped through this mod? (Other methods e.g. through vanilla is not included)
	"Should drop equipment" = false

#Settings for attribute modifiers
[attributes]
	#Health will be multiplied by difficulty*0.016*x. Set to 0 to disable
	"Health Increase Multiplier" = 1.0
	#Health will be multiplied by at maximum this. Set to 0 means no limit
	"Max Health Increase" = 5.0
	#Round health to the nearest x. Set to 0 to disable
	"Round HP" = 0.5
	#Damage will be multiplied by difficulty*0.008*x. Set to 0 to disable
	"Damage Increase Multiplier" = 1.0
	#Damage will be multiplied by at maximum this. Set to 0 means no limit
	"Max Damage Increase" = 3.0
	#Speed will be increased by difficulty*0.0008*x. Set to 0 to disable
	"Speed Increase" = 1.0
	#Maximum increase in speed
	#Range: 0.0 ~ 1.0
	"Max Speed" = 0.1
	#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
	"Knockback Increase" = 1.0
	#Maximum increase in knockback
	"Max Knockback" = 0.5
	#Magic resistance will be increased by difficulty*0.0016*x. Set to 0 to disable
	"Magic Resistance Increase" = 1.0
	#Maximum increase in magic resistance. Magic reduction is percentage
	#Range: 0.0 ~ 1.0
	"Max Magic Resistance" = 0.4
	#Projectile Damage will be multiplied by 1+difficulty*0.008*x. Set to 0 to disable
	"Projectile Damage Increase" = 1.0
	#Projectile damage will be multiplied by maximum of this
	"Max Projectile Damage" = 2.0

